=== JovanCorilic/XML-Projekat/xml/Patent/P-1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://www.ftn.uns.rs/P-1" xmlns:P-1="http://www.ftn.uns.rs/P-1">

    <xs:element name="P-1">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="popunjava_zavod" type="P-1:tipPopunjavaZavod"/>
                <xs:element name="naslov" type="xs:string"/>
                <xs:element name="naziv_pronalaska" type="P-1:tipNazivPronalaska"/>
                <xs:element name="podnosilac_prijave" type="P-1:tipPodnosilacPrijave"/>
                <xs:element name="pronalazac" type="P-1:tipPronalazac"/>
                <xs:element name="punomocnik" type="P-1:tipPunomocnik"/>
                <xs:element name="dostavljanje" type="P-1:tipDostavljanje"/>
                <xs:element name="tip_prijave" type="P-1:tipTipPrijave"/>
                <xs:element name="zahtev_za_priznanje_prava_prvenstva_iz_ranijih_prijava"
                    type="P-1:tipZahtevZaPriznanjePravaPrvenstvaIzRanijihPrijava"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="tipPopunjavaZavod">
        <xs:sequence>
            <xs:element name="broj_prijave" type="xs:int"/>
            <xs:element name="datum_prijema" type="xs:string"/>
            <xs:element name="priznati_datum_podnosenja" type="xs:string"/>
            <xs:element name="pecat_i_potpis" type="xs:string"/>
            <xs:element name="drzava" type="xs:string"/>
            <xs:element name="ustanova" type="xs:string"/>
            <xs:element name="adresa" type="P-1:tipAdresa"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="tipAdresa">
        <xs:sequence>
            <xs:element name="naziv_ulice" type="xs:string"/>
            <xs:element name="broj_ulice" type="xs:int"/>
            <xs:element name="grad" type="xs:string"/>
            <xs:element name="postanski_broj" type="xs:int"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="tipNazivPronalaska">
        <xs:sequence>
            <xs:element name="srpski_naziv" type="xs:string"/>
            <xs:element name="engleski_naziv" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="tipPodnosilacPrijave">
        <xs:sequence>
            <xs:element name="licne_informacije" type="P-1:tipLicneInformacije"/>
            <xs:element name="drzavljanstvo" type="xs:string"/>
            <xs:element name="je_pronalazac" type="xs:boolean"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="tipOsoba">
        <xs:sequence>
            <xs:element name="ime" type="xs:string"/>
            <xs:element name="prezime" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="tipFirma">
        <xs:sequence>
            <xs:element name="poslovno_ime" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="tipPrebivaliste">
        <xs:sequence>
            <xs:element name="ulica" type="xs:string"/>
            <xs:element name="broj_ulice" type="xs:int" nillable="true"/>
            <xs:element name="postanski_broj" type="xs:int" nillable="true"/>
            <xs:element name="grad" type="xs:string"/>
            <xs:element name="drzava" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="tipKontakt">
        <xs:sequence>
            <xs:element name="broj_telefona" type="xs:string"/>
            <xs:element name="broj_faksa" type="xs:string"/>
            <xs:element name="e-posta" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="tipNaziv">
        <xs:choice>
            <xs:element name="osoba" type="P-1:tipOsoba" minOccurs="0"/>
            <xs:element name="firma" type="P-1:tipFirma" minOccurs="0"/>
        </xs:choice>
    </xs:complexType>
    <xs:complexType name="tipLicneInformacije">
        <xs:sequence>
            <xs:element name="naziv" type="P-1:tipNaziv"/>
            <xs:element name="prebivaliste" type="P-1:tipPrebivaliste"/>
            <xs:element name="kontakt" type="P-1:tipKontakt"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="tipPronalazac">
        <xs:sequence>
            <xs:element name="da_li_pronalazac_zeli_da_bude_naveden" type="xs:boolean"/>
            <xs:element name="licne_informacije" type="P-1:tipLicneInformacije"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="tipPunomocnik">
        <xs:sequence>
            <xs:element name="da_li_je_punomocnik_za_zastupanje" type="xs:boolean"/>
            <xs:element name="da_li_je_punomocnik_za_prijem_pismena" type="xs:boolean"/>
            <xs:element name="da_li_je_zajednicki_predstavnik" type="xs:boolean"/>
            <xs:element name="licne_informacije" type="P-1:tipLicneInformacije"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="tipDostavljanje">
        <xs:sequence>
            <xs:element name="adresa" type="P-1:tipAdresa"/>
            <xs:element name="nacin" type="P-1:tipNacin"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="tipNacin">
        <xs:sequence>
            <xs:element name="dostavljanje_pismena_iskljucivo_elektronskim_putem" type="xs:boolean"/>
            <xs:element name="dostavljanje_pismena_u_papirnoj_formi" type="xs:boolean"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="tipTipPrijave">
        <xs:sequence>
            <xs:element name="da_li_je_dopunska_prijava" type="xs:boolean"/>
            <xs:element name="da_li_je_izdvojena_prijava" type="xs:boolean"/>
            <xs:element name="broj_prvobitne_prijave" type="xs:int"/>
            <xs:element name="datum_podnosenja_prvobitne_prijave" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="tipZahtevZaPriznanjePravaPrvenstvaIzRanijihPrijava">
        <xs:sequence>
            <xs:element maxOccurs="unbounded" minOccurs="0" name="ranija_prijava"
                type="P-1:tipRanijaPrijava"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="tipRanijaPrijava">
        <xs:sequence>
            <xs:element name="datum_podnosenja_ranije_prijave" type="xs:string"/>
            <xs:element name="broj_ranije_prijave" type="xs:string"/>
            <xs:element name="dvoslovna_oznaka_drzave_ili_organizacije" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== JovanCorilic/XML-Projekat/xml/Patent/Parser-Patent/data/P-1-2.xml
<?xml version="1.0" encoding="UTF-8"?>
<P-1 id="2"
    xmlns="http://www.ftn.uns.rs/P-1"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.ftn.uns.rs/P-1 file:/C:/Users/Kssbc/Documents/GitHub/XML-Projekat/xml/Patent/P-1.xsd">
    <popunjava_zavod>
        
        <broj_prijave>5</broj_prijave>
        <datum_prijema>10.9.2020</datum_prijema>
        <priznati_datum_podnosenja>15.9.2020</priznati_datum_podnosenja>
        <pecat_i_potpis>Nevazno</pecat_i_potpis>
        
        
        <drzava>Republika Srbija</drzava>
        <ustanova>Zavod za intelektualnu svojinu</ustanova>
        <adresa>
            <naziv_ulice>Kneginje LJubice</naziv_ulice> 
            <broj_ulice>5</broj_ulice>
            <grad>Beograd</grad>
            <postanski_broj>11000</postanski_broj>
        </adresa>
     
    </popunjava_zavod>
    
    <naslov>ZAHTEV ZA PRIZNANJE PATENTA</naslov>
        
    <naziv_pronalaska>
        <srpski_naziv>Čistač veša</srpski_naziv>
        <engleski_naziv>Cleaner</engleski_naziv>
    </naziv_pronalaska>
        
    <podnosilac_prijave>
        <licne_informacije>
            <naziv>
                <firma>
                    <poslovno_ime>MegaClean</poslovno_ime>
                </firma>
            </naziv>
            
            <prebivaliste>
                <ulica>Marković</ulica>
                <broj_ulice>50</broj_ulice>
                <postanski_broj>21000</postanski_broj>
                <grad>Novi Sad</grad>
                <drzava>Srbija</drzava>
            </prebivaliste>
            
            <kontakt>
                <broj_telefona>1654151154</broj_telefona>
                <broj_faksa>154146541645</broj_faksa>
                <e-posta>@gmail.com</e-posta>
            </kontakt>
        </licne_informacije>
        <drzavljanstvo>Srpska firma</drzavljanstvo>
        <je_pronalazac>false</je_pronalazac>
    </podnosilac_prijave>
        
        <!-- <da_li_su_ostali_podnosioci_prijave_navedeni></da_li_su_ostali_podnosioci_prijave_navedeni> -->

    <pronalazac>
        <da_li_pronalazac_zeli_da_bude_naveden>false</da_li_pronalazac_zeli_da_bude_naveden>
        <licne_informacije>
            <naziv>
                
                
               
            </naziv>
            
            <prebivaliste>
                <ulica></ulica>
                <broj_ulice xsi:nil = "true"></broj_ulice>
                <postanski_broj xsi:nil = "true"></postanski_broj>
                <grad></grad>
                <drzava></drzava>
            </prebivaliste>
            
            <kontakt>
                <broj_telefona></broj_telefona>
                <broj_faksa></broj_faksa>
                <e-posta></e-posta>
            </kontakt>
        </licne_informacije>
    </pronalazac>
        
        <!-- <da_li_su_ostali_pronalazaci_navedeni></da_li_su_ostali_pronalazaci_navedeni> -->
    
    <punomocnik>
        <!-- Ili je jedno ili drugo -->
        <da_li_je_punomocnik_za_zastupanje>false</da_li_je_punomocnik_za_zastupanje>
        <da_li_je_punomocnik_za_prijem_pismena>true</da_li_je_punomocnik_za_prijem_pismena>
        <!-- Moze da bude tu a ne mora -->
        <da_li_je_zajednicki_predstavnik>false</da_li_je_zajednicki_predstavnik>
        
        <licne_informacije>
            <naziv>
                
                
                <firma>
                    <poslovno_ime>Advokat Max</poslovno_ime>
                </firma>
            </naziv>
            
            <prebivaliste>
                <ulica>Neštanska</ulica>
                <broj_ulice>12</broj_ulice>
                <postanski_broj>21000</postanski_broj>
                <grad>Novi Sad</grad>
                <drzava>Srbija</drzava>
            </prebivaliste>
            
            <kontakt>
                <broj_telefona>546546514</broj_telefona>
                <broj_faksa>56125454</broj_faksa>
                <e-posta>@gmail.com</e-posta>
            </kontakt>
        </licne_informacije>
        
    </punomocnik>
    
    <dostavljanje>
        <adresa>
            <naziv_ulice>Neksilija</naziv_ulice>
            <broj_ulice>45</broj_ulice>
            
            <grad>Novi Sad</grad>
            <postanski_broj>21000</postanski_broj>
        </adresa>
        
        <nacin>
            <dostavljanje_pismena_iskljucivo_elektronskim_putem>false</dostavljanje_pismena_iskljucivo_elektronskim_putem>
            <dostavljanje_pismena_u_papirnoj_formi>true</dostavljanje_pismena_u_papirnoj_formi>
        </nacin>
    </dostavljanje>
    
    <tip_prijave>
        <da_li_je_dopunska_prijava>true</da_li_je_dopunska_prijava>
        <da_li_je_izdvojena_prijava>false</da_li_je_izdvojena_prijava>
        
        <broj_prvobitne_prijave>9</broj_prvobitne_prijave>
        <datum_podnosenja_prvobitne_prijave>10.8.2020</datum_podnosenja_prvobitne_prijave>
    </tip_prijave>
    
    <zahtev_za_priznanje_prava_prvenstva_iz_ranijih_prijava>
        <!-- Ovo je lista -->
        <ranija_prijava>
            <datum_podnosenja_ranije_prijave>10.8.2020</datum_podnosenja_ranije_prijave>
            <broj_ranije_prijave>9</broj_ranije_prijave>
            <dvoslovna_oznaka_drzave_ili_organizacije>MA</dvoslovna_oznaka_drzave_ili_organizacije>
        </ranija_prijava>
        
        
        
        <!-- <da_li_su_podaci_o_ostalim_pravima_prvenstva_navedena></da_li_su_podaci_o_ostalim_pravima_prvenstva_navedena> -->
    </zahtev_za_priznanje_prava_prvenstva_iz_ranijih_prijava>
</P-1>
