=== JovanCorilic/XML-Projekat/xml/a_jedan/src/main/resources/A-1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xs:element name="A-1">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="zavod_za_intelektualnu_svoinu"/>
                <xs:element name="adresa">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="grad"/>
                            <xs:element name="naziv_ulice"/>
                            <xs:element name="broj_ulice"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="obrazac"/>
                <xs:element name="naslov"/>
                <xs:choice>
                    <xs:element name="podnosilac_lice">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element name="ime"/>
                                <xs:element name="prezime"/>
                                <xs:element name="adresa"/>
                                <xs:element name="drzavljanstvo"/>
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>
                    <xs:element name="podnosilac_firma">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element name="poslovno_ime"/>
                                <xs:element name="sediste_nosioca_autorskog"/>
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>
                </xs:choice>
                <xs:element name="telefon"/>
                <xs:element name="email"/>
                <xs:choice>
                    <xs:element name="pseudonim"/>
                    <xs:element name="znak_autora"/>
                </xs:choice>
                <xs:element name="autor">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="ime"/>
                            <xs:element name="prezime"/>
                            <xs:element name="adresa">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="grad"/>
                                        <xs:element name="naziv_ulice"/>
                                        <xs:element name="broj_ulice"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="naslov"/>
                <xs:sequence minOccurs="0">
                    <xs:element minOccurs="1" name="alternativni_naslov"/>
                </xs:sequence>
                <xs:element minOccurs="0" name="podaci_o_zasnivanju">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element minOccurs="1" name="podaci_o_naslovu"/>
                            <xs:element name="podaci_o_autoru">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="ime"/>
                                        <xs:element name="prezime"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="vrsti_autorskog_dela"/>
                <xs:element name="forma_zapisa_autorskog_dela"/>
                <xs:element name="podnosioci">
                    <xs:complexType>
                        <xs:sequence maxOccurs="unbounded">
                            <xs:element name="podnosilac">
                                <xs:complexType>
                                    <xs:choice>
                                        <xs:element name="ziv">
                                            <xs:complexType>
                                                <xs:sequence>
                                                  <xs:element name="prezime"/>
                                                  <xs:element name="ime"/>
                                                  <xs:element name="adresa">
                                                  <xs:complexType>
                                                  <xs:sequence>
                                                  <xs:element name="grad"/>
                                                  <xs:element name="naziv_ulice"/>
                                                  <xs:element name="broj_ulice"/>
                                                  </xs:sequence>
                                                  </xs:complexType>
                                                  </xs:element>
                                                  <xs:element name="drzavljanstvo"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="mrtav">
                                            <xs:complexType>
                                                <xs:sequence>
                                                  <xs:element name="prezime"/>
                                                  <xs:element name="ime"/>
                                                  <xs:element name="godina_smrti"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="anoniman">
                                            <xs:complexType>
                                                <xs:sequence>
                                                  <xs:element name="delo_delo_anonimnog_autora"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:choice>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="da_li_je_delo_stvoreno_u_radnom_odnosu"/>
                <xs:choice>
                    <xs:element name="nacin_koriscenja_autorskog_dela"/>
                    <xs:element name="nameravani_nacin_korišćenja_autorskog_dela"/>
                </xs:choice>
                <xs:element name="nosilac_prijave">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="podnosilac_prijave"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="podneti_prilozi_zahtev">
                    <xs:complexType>
                        <xs:sequence maxOccurs="unbounded">
                            <xs:element name="popunjava">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="ime"/>
                                        <xs:element name="prezime"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="prilozi_prijave"/>
                            <xs:element name="opis_autorskog_dela"/>
                            <xs:element name="primer_autorskog_dela"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="broj_prijave"/>
                <xs:element name="datum_podnosenja"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== JovanCorilic/XML-Projekat/xml/a_jedan/src/main/resources/temp.xml
<A-1 xmlns:pred="https://1564.com/predicate" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:/C:/Users/User/Desktop/A-1.xsd">
    <zavod_za_intelektualnu_svoinu>LND D.O.O.</zavod_za_intelektualnu_svoinu>
    <adresa>
        <grad>Novi Sad</grad>
        <naziv_ulice>Marka Pavlica</naziv_ulice>
        <broj_ulice>45</broj_ulice>
    </adresa>
    <obrazac>Obrazac za patente</obrazac>
    <x:naslov xmlns:x="https://1564.com" property="pred:naslov">Patent za zavrnut elektromagnetni uredjaj</x:naslov>
    <podnosilac_firma>
        <poslovno_ime>Misic i Pavlic Izumi D.O.O.</poslovno_ime>
        <sediste_nosioca_autorskog>Novi Sad</sediste_nosioca_autorskog>
    </podnosilac_firma>
    <telefon>035/0365-035-30</telefon>
    <email>SlavkoMisic@MiLIzumi</email>
    <pseudonim>Dr. Strija</pseudonim>
    <autor>
        <ime>Slavko</ime>
        <prezime>Misic</prezime>
        <adresa>
            <grad>Novi Sad</grad>
            <naziv_ulice>Bulevar Oslobodjenja</naziv_ulice>
            <broj_ulice>12</broj_ulice>
        </adresa>
    </autor>
    <naslov>Patent za zavrnut elektromagnetni uredjaj</naslov>
    <vrsti_autorskog_dela>patent</vrsti_autorskog_dela>
    <forma_zapisa_autorskog_dela>tekst</forma_zapisa_autorskog_dela>
    <podnosioci>
        <podnosilac>
            <anoniman>
                <delo_delo_anonimnog_autora>zavrnut elektromagnetni uredjaj</delo_delo_anonimnog_autora>
            </anoniman>
        </podnosilac>
        <podnosilac>
            <mrtav>
                <prezime>Palvic</prezime>
                <ime>Sima</ime>
                <godina_smrti>2022</godina_smrti>
            </mrtav>
        </podnosilac>
    </podnosioci>
    <da_li_je_delo_stvoreno_u_radnom_odnosu>da</da_li_je_delo_stvoreno_u_radnom_odnosu>
    <nameravani_nacin_korišćenja_autorskog_dela>masinski</nameravani_nacin_korišćenja_autorskog_dela>
    <nosilac_prijave>
        <podnosilac_prijave>slavko</podnosilac_prijave>
    </nosilac_prijave>
    <podneti_prilozi_zahtev>
        <popunjava>
            <ime>Slavko</ime>
            <prezime>Misic</prezime>
        </popunjava>
        <prilozi_prijave>patent</prilozi_prijave>
        <opis_autorskog_dela>bolji magnet</opis_autorskog_dela>
        <primer_autorskog_dela>demonstracija.mp4</primer_autorskog_dela>
    </podneti_prilozi_zahtev>
    <x:broj_prijave xmlns:x="https://1564.com" property="pred:broj_prijave">5415156</x:broj_prijave>
    <datum_podnosenja>11.12.2023</datum_podnosenja>
</A-1>

=== JovanCorilic/XML-Projekat/xml/a_jedan/src/main/resources/instance1.xml
<?xml version="1.0" encoding="UTF-8"?>
<A-1 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="file:/C:/Users/User/Desktop/a_jedan/a_jedan/src/main/resources/A-1.xsd">
    <autor>
        <ime>
        </ime>
        <prezime>
        </prezime>
        <adresa>
            <grad>
            </grad>
            <naziv_ulice>
            </naziv_ulice>
            <broj_ulice>
            </broj_ulice>
        </adresa>
    </autor>
    <zavod_za_intelektualnu_svoinu>
    </zavod_za_intelektualnu_svoinu>
    <adresa>
        <grad>
        </grad>
        <naziv_ulice>
        </naziv_ulice>
        <broj_ulice>
        </broj_ulice>
    </adresa>
    <obrazac>
    </obrazac>
    <naslov>
    </naslov>
    <podnosilac_firma>
        <poslovno_ime>
        </poslovno_ime>
        <sediste_nosioca_autorskog>
        </sediste_nosioca_autorskog>
    </podnosilac_firma>
    <telefon>
    </telefon>
    <email>
    </email>
    <znak_autora>
    </znak_autora>
    <naslov>
    </naslov>
    <vrsti_autorskog_dela>
    </vrsti_autorskog_dela>
    <forma_zapisa_autorskog_dela>
    </forma_zapisa_autorskog_dela>
    <podnosioci>
        <podnosilac>
            <anoniman>
                <delo_delo_anonimnog_autora>
                </delo_delo_anonimnog_autora>
            </anoniman>
        </podnosilac>
        <podnosilac>
            <ziv>
                <prezime>
                </prezime>
                <ime>
                </ime>
                <adresa>
                    <grad>
                    </grad>
                    <naziv_ulice>
                    </naziv_ulice>
                    <broj_ulice>
                    </broj_ulice>
                </adresa>
                <drzavljanstvo>
                </drzavljanstvo>
            </ziv>
        </podnosilac>
    </podnosioci>
    <da_li_je_delo_stvoreno_u_radnom_odnosu>
    </da_li_je_delo_stvoreno_u_radnom_odnosu>
    <nacin_koriscenja_autorskog_dela>
    </nacin_koriscenja_autorskog_dela>
    <nosilac_prijave>
        <podnosilac_prijave>
        </podnosilac_prijave>
    </nosilac_prijave>
    <podneti_prilozi_zahtev>
        <popunjava>
            <ime>
            </ime>
            <prezime>
            </prezime>
        </popunjava>
        <prilozi_prijave>
        </prilozi_prijave>
        <opis_autorskog_dela>
        </opis_autorskog_dela>
        <primer_autorskog_dela>
        </primer_autorskog_dela>
        <popunjava>
            <ime>
            </ime>
            <prezime>
            </prezime>
        </popunjava>
        <prilozi_prijave>
        </prilozi_prijave>
        <opis_autorskog_dela>
        </opis_autorskog_dela>
        <primer_autorskog_dela>
        </primer_autorskog_dela>
    </podneti_prilozi_zahtev>
    <broj_prijave>
    </broj_prijave>
    <datum_podnosenja>
    </datum_podnosenja>
</A-1>
