=== JovanCorilic/XML-Projekat/ZIG-APP/zig-back-app/src/main/resources/data/xsd/zig.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace = "http://ftn.uns.ac.rs/zig"
    xmlns = "http://ftn.uns.ac.rs/zig"
    elementFormDefault="qualified">
    
    <xs:element name = "trademark">
        
        <xs:complexType>
            
            <xs:sequence>
                
                <xs:element  name = "applicant" type="subject_info" minOccurs = "1" maxOccurs = "1"/>
                <xs:element  name = "proxy" type="subject_info" minOccurs = "1" maxOccurs = "1"/>
                <xs:element  name = "common_representative" type="subject_info" minOccurs = "1" maxOccurs = "1"/>
                
                <xs:element  name = "trademark_info" type="trademark_info" minOccurs = "1" maxOccurs = "1"/>
                
                <xs:element  name = "nice_classification" type="nice_classification" minOccurs = "1" maxOccurs = "1"/>
                
                <xs:element  name = "requested_right_of_priority_and_basis" type="xs:string" minOccurs = "1" maxOccurs = "1"/>
                
                <xs:element  name = "fee" type="fee" minOccurs = "1" maxOccurs = "1"/>
                
                <xs:element  name = "institution" type="institution" minOccurs = "1" maxOccurs = "1"/>
                
                <xs:element  name = "trademark_number" type="trademark_number" minOccurs = "1" maxOccurs = "1"/>
                
                <xs:element  name = "date" type="xs:long" minOccurs = "1" maxOccurs = "1"/><!-- Broj milisekundi -->
                

            </xs:sequence>
          
            <xs:attribute name="trademark_id" type="xs:string"/>

        </xs:complexType>
  
    </xs:element>

    <xs:simpleType name="trademark_number">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{6}\/\d{2}"/> <!-- 0-999\0-99 -->
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="institution">
        <xs:sequence><!-- XS:STRING -> FILE LOCATION ON DISK-->

            <xs:element  name = "trademark_sample" type="xs:string" minOccurs = "1" maxOccurs = "1"/>
            <xs:element  name = "list_of_goods_and_services" type="xs:string" minOccurs = "1" maxOccurs = "1"/>

            <xs:element  name = "power_of_attorney" type="xs:string" minOccurs = "1" maxOccurs = "1"/>
            <xs:element  name = "general_power_of_attorney_previously_submitted" type="xs:boolean" minOccurs = "1" maxOccurs = "1"/>
            <xs:element  name = "power_of_attorney_will_be_delivered_later" type="xs:boolean" minOccurs = "1" maxOccurs = "1"/>
            
            <xs:element  name = "general_act" type="xs:string" minOccurs = "1" maxOccurs = "1"/>
            
            <xs:element  name = "proof_of_priority" type="xs:string" minOccurs = "1" maxOccurs = "1"/>

            <xs:element  name = "proof_of_fee_payment" type="xs:string" minOccurs = "1" maxOccurs = "1"/>

        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="fee">
        <xs:sequence>
            <xs:element  name = "basic" type="xs:long" minOccurs = "1" maxOccurs = "1"/>
            <!-- <xs:element  name = "basic" type="fee_additional" minOccurs = "1" maxOccurs = "1"/> -->
            <xs:element  name = "nice_class" type="xs:long" minOccurs = "1" maxOccurs = "1"/>
            <xs:element  name = "graphical_solution" type="xs:long" minOccurs = "1" maxOccurs = "1"/>
        </xs:sequence>
    </xs:complexType>

    <!-- <xs:complexType name="fee_additional">
        <xs:choice>
            <xs:element  name = "nice_class" type="xs:decimal" minOccurs = "1" maxOccurs = "1"/>
            <xs:element  name = "graphical_solution" type="xs:decimal" minOccurs = "1" maxOccurs = "1"/>
        </xs:choice>
    </xs:complexType> -->

    <xs:simpleType name="nice_classification">
        <xs:restriction base="xs:string">
            <xs:enumeration value="class 1"/>
            <xs:enumeration value="class 2"/>
            <xs:enumeration value="class 3"/>
            <xs:enumeration value="class 4"/>
            <xs:enumeration value="class 5"/>
            <xs:enumeration value="class 6"/>
            <xs:enumeration value="class 7"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="trademark_info">
        <xs:sequence>
            <xs:element  name = "trademark_type" type="trademark_type" minOccurs = "1" maxOccurs = "1"/>
            <xs:element  name = "trademark_appearance" type="trademark_appearance" minOccurs = "1" maxOccurs = "1"/>
            <xs:element  name = "trademark_view" type="xs:string" minOccurs = "1" maxOccurs = "1"/>
            <xs:element  name = "trademark_colors" type="trademark_colors" minOccurs = "1" maxOccurs = "1"/>
            <xs:element  name = "trademark_transliteration" type="xs:string" minOccurs = "1" maxOccurs = "1"/>
            <xs:element  name = "trademark_translation" type="xs:string" minOccurs = "1" maxOccurs = "1"/>
            <xs:element  name = "trademark_description" type="xs:string" minOccurs = "1" maxOccurs = "1"/>
            
        </xs:sequence>
    </xs:complexType>

    


    <xs:complexType name="trademark_colors">
        <xs:sequence>
            <xs:element  name = "trademark_color" type="xs:string" minOccurs = "1" maxOccurs = "unbounded"/>
        </xs:sequence>
    </xs:complexType>
        
    <xs:simpleType name="trademark_appearance">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Verbal Trademark"/>
            <xs:enumeration value="Graphic Trademark"/>
            <xs:enumeration value="Combined Trademark"/>
            <xs:enumeration value="Three-Dimensional Trademark"/>
            <xs:enumeration value="Another Trademark"/>
        </xs:restriction>
    </xs:simpleType>


    <xs:simpleType name="trademark_type">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Individual Trademark"/>
            <xs:enumeration value="Collective Trademark"/>
            <xs:enumeration value="Guarantee Trademark"/>
        </xs:restriction>
    </xs:simpleType>
    


    <xs:complexType name="subject_info">
        <xs:sequence>
            <xs:element name = "subject" type="subject" minOccurs = "1" maxOccurs = "1"/>
            <xs:element name = "address" type="address" minOccurs = "1" maxOccurs = "1"/>
            
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="address">
        <xs:sequence>
            <xs:element name = "street_name" type="xs:string" minOccurs = "1" maxOccurs = "1"/>
            <xs:element name = "street_number" type="xs:string" minOccurs = "1" maxOccurs = "1"/>
            <xs:element name = "zip_code" type="xs:string" minOccurs = "1" maxOccurs = "1"/>
            <xs:element name = "city" type="xs:string" minOccurs = "1" maxOccurs = "1"/>
            <xs:element name = "country" type="xs:string" minOccurs = "1" maxOccurs = "1"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="subject">
        <xs:choice>
            <xs:element name = "company" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="user" type="user" minOccurs="1" maxOccurs="1" />
        </xs:choice>
    </xs:complexType>
        
    <xs:complexType name="user">
        <xs:sequence>
            <xs:element name = "first_name" type="xs:string" minOccurs = "1" maxOccurs = "1"/>
            <xs:element name = "last_name" type="xs:string" minOccurs = "1" maxOccurs = "1"/>
        </xs:sequence>
    </xs:complexType>
        
    
    
    
</xs:schema>

=== JovanCorilic/XML-Projekat/ZIG-APP/zig-back-app/src/main/resources/data/xsd/zig_best.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- Created with Liquid Technologies Online Tools 1.0 (https://www.liquid-technologies.com) -->
<trademark xmlns="http://ftn.uns.ac.rs/trademark" xsi:schemaLocation=" http://ftn.uns.ac.rs/trademark file:\C:\Users\vaske\Desktop\XML20222023\ZIG-APP\zig-back-app\src\main\resources\data\xsd\zig.xsd" trademark_id="string" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <applicant>
    <subject>
      <user>
        <first_name>string</first_name>
        <last_name>string</last_name>
      </user>
    </subject>
    <address>
      <street_name>string</street_name>
      <street_number>string</street_number>
      <zip_code>string</zip_code>
      <city>string</city>
      <country>string</country>
    </address>
    
  </applicant>
  <proxy>
    <subject>
      <company>string</company>
    </subject>
    <address>
      <street_name>string</street_name>
      <street_number>string</street_number>
      <zip_code>string</zip_code>
      <city>string</city>
      <country>string</country>
    </address>
  </proxy>
  <common_representative>
    <subject>
      <company>string</company>
    </subject>
    <address>
      <street_name>string</street_name>
      <street_number>string</street_number>
      <zip_code>string</zip_code>
      <city>string</city>
      <country>string</country>
    </address>
  </common_representative>
  <trademark_info>
    <trademark_type>Guarantee Trademark</trademark_type>
    <trademark_appearance>Three-Dimensional Trademark</trademark_appearance>
    <trademark_view>string</trademark_view>
    <trademark_colors>
      <trademark_color>string</trademark_color>
    </trademark_colors>
    <trademark_transliteration>string</trademark_transliteration>
    <trademark_translation>string</trademark_translation>
    <trademark_description>string</trademark_description>
  </trademark_info>
  <nice_classification>class 2</nice_classification>
  <requested_right_of_priority_and_basis>string</requested_right_of_priority_and_basis>
  <fee>
    <basic>47601202349058</basic>
    <nice_class>23</nice_class>
    <graphical_solution>11488002349058</graphical_solution>
  </fee>
  <institution>
    <trademark_sample>string</trademark_sample>
    <list_of_goods_and_services>string</list_of_goods_and_services>
    <power_of_attorney>string</power_of_attorney>
    <general_power_of_attorney_previously_submitted>false</general_power_of_attorney_previously_submitted>
    <power_of_attorney_will_be_delivered_later>1</power_of_attorney_will_be_delivered_later>
    <general_act>string</general_act>
    <proof_of_priority>string</proof_of_priority>
    <proof_of_fee_payment>string</proof_of_fee_payment>
  </institution>
  <trademark_number>445974/99</trademark_number>
  <date>1870</date>
</trademark>
